### ISSUE TITLE
Assignment 2 - Todo List

### ISSUE THREAD

**Issue by JiminKim-dev** [JiminKim-dev/wanted-pre-onboarding-challenge-fe-1#5]
## 기능 요청사항
Todo List API를 호출하여 Todo List CRUD 기능을 구현한다.

## 요청 세부사항
- Todo List API를 호출하여 Todo List CRUD 기능을 구현한다.
    - [ ] 목록 / 상세 영역으로 나누어 구현해주세요
    - [ ] Todo 목록을 볼 수 있습니다.
    - [ ] Todo 추가 버튼을 클릭하면 할 일이 추가 됩니다.
    - [ ] Todo 수정 버튼을 클릭하면 수정 모드를 활성화하고, 수정 내용을 제출하거나 취소할 수 있습니다.
    - [ ] Todo 삭제 버튼을 클릭하면 해당 Todo를 삭제할 수 있습니다.
- 한 화면 내에서 Todo List와 개별 Todo의 상세를 확인할 수 있도록 해주세요.
    - [ ] 새로고침을 했을 때 현재 상태가 유지되어야 합니다.
    - [ ] 개별 Todo를 조회 순서에 따라 페이지 뒤로가기를 통하여 조회할 수 있도록 해주세요.
- 한 페이지 내에서 새로고침 없이 데이터가 정합성을 갖추도록 구현해주세요
    - [ ] 수정되는 Todo의 내용이 목록에서도 실시간으로 반영되어야 합니다
